name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".frontmatter/**"
      - ".vscode/**"
      - "README.md"
      - .gitignore
permissions: {}

jobs:
  create-release:
    permissions:
      contents: write 
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: 'true'
          persist-credentials: false

      - name: Install Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo --minify

      - name: Delete old Release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        continue-on-error: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            // 獲取最新的發布資訊
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner,
              repo,
            });
    
            // 判斷是否成功獲取到最新發布的資訊
            if (latestRelease && latestRelease.data && latestRelease.data.id) {
              // 如果有最新發布，則進行刪除
              await github.rest.repos.deleteRelease({
                owner,
                repo,
                release_id: latestRelease.data.id,
              });
              console.log(`Release id ${latestRelease.data.id} has been deleted.`);
            } else {
              // 如果沒有獲取到最新發布的資訊，則輸出提示訊息
              console.log("No latest release found or failed to retrieve it.");
            }

      - name: Retrieve current Date Time in Asia/Taipei
        shell: bash
        run: echo "START_TIME=$(TZ=":Asia/Taipei" date +'%Y-%m-%d-%H:%M:%S')" >> $GITHUB_ENV

      - name: Archive Release
        uses: thedoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554 # 0.7.6
        with:
          type: 'zip'
          filename: 'release-${{ env.START_TIME }}.zip'
          #exclusions: '*.git* /*node_modules/* .editorconfig'
          path: public
     
      - name: Publish Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          prerelease: false
          tag_name: latest
          body: "建立於台灣時間: ${{ env.START_TIME }}"
          files: |
            release-${{ env.START_TIME }}.zip